book commit
DenisBogusevich/Online_Book_Store pull request #1
Opened 2023-10-18 01:41 UTC by DenisBogusevich

2023-10-18 21:22 UTC, RomanYuzviak approved these changes
Looks great!

2023-10-20 08:53 UTC, liliia-ponomarenko requested changes
Good job! Let’s fix a few mistakes ;)

2023-10-20 08:53 UTC, liliia-ponomarenko commented on pom.xml
> +</project>
add one empty line

2023-10-20 08:53 UTC, liliia-ponomarenko commented on src/main/java/onlinebookstore/exception/DataProcessingException.java
> +    public DataProcessingException(String s, Exception e) {
Don’t  use abbreviations 
```suggestion
    public DataProcessingException(String message, Exception exception) {
```

2023-10-20 08:53 UTC, liliia-ponomarenko commented on src/main/java/onlinebookstore/repository/impl/BookRepositoryImpl.java
> +import jakarta.persistence.EntityNotFoundException;
better create your custom EntityNotFoundException

2023-10-20 08:53 UTC, liliia-ponomarenko commented on src/main/java/onlinebookstore/service/impl/BookServiceImpl.java
> +@Component
```suggestion
@Service
```
Use annotation Service for classes  with business logic

2023-10-20 08:53 UTC, liliia-ponomarenko commented on src/main/java/onlinebookstore/service/impl/BookServiceImpl.java
> +    @Autowired
As of Spring Framework 4.3, an @Autowired annotation on such a constructor is no longer necessary if the target bean defines only one constructor to begin with. See [note here ](https://docs.spring.io/spring-framework/reference/core/beans/annotation-config/autowired.html)Let’s check it ;)

2023-10-27 09:47 UTC, liliia-ponomarenko approved these changes
LGTM 🔥

2024-01-25 01:43 UTC, closed without merging