Category
DenisBogusevich/Online_Book_Store pull request #12
Opened 2023-12-11 02:48 UTC by DenisBogusevich

2023-12-11 08:11 UTC, Elena-Bruyako requested changes
Good job! Lets improve your solution!

2023-12-11 08:11 UTC, Elena-Bruyako commented on src/main/java/onlinebookstore/controler/CategoryController.java
> +
```suggestion
```

2023-12-11 08:11 UTC, Elena-Bruyako commented on src/main/java/onlinebookstore/controler/CategoryController.java
> +    public List<BookDtoWithoutCategoryIds> getBooksByCategoryId(@PathVariable Long id) {
```suggestion
    public List<BookDtoWithoutCategoryIds> getBooksByCategoryId(@PathVariable @Positive Long id) {
```

2023-12-11 08:11 UTC, Elena-Bruyako commented on src/main/java/onlinebookstore/controler/CategoryController.java
> +    public CategoryDto updateCategory(@PathVariable Long id,
```suggestion
    public CategoryDto updateCategory(@PathVariable @Positive Long id,
```

2023-12-11 08:11 UTC, Elena-Bruyako commented on src/main/java/onlinebookstore/controler/CategoryController.java
> +                                      @RequestBody CategoryRequestDto categoryDto) {
```suggestion
                                      @RequestBody @Valid CategoryRequestDto categoryDto) {
```

2023-12-11 08:11 UTC, Elena-Bruyako commented on src/main/java/onlinebookstore/controler/CategoryController.java
> +    public void deleteCategoryById(@PathVariable Long id) {
```suggestion
    public void deleteCategoryById(@PathVariable @Positive Long id) {
```

2023-12-11 08:11 UTC, Elena-Bruyako commented on src/main/java/onlinebookstore/controler/CategoryController.java
> +@RestController
Please add Swagger documentation here

2023-12-11 08:11 UTC, Elena-Bruyako commented on src/main/java/onlinebookstore/controler/CategoryController.java
> +@RequestMapping("/categories")
`@Validated`

2023-12-11 08:11 UTC, Elena-Bruyako commented on src/main/java/onlinebookstore/controler/CategoryController.java
> +    public CategoryDto createCategory(@RequestBody CategoryRequestDto categoryRequestDto) {
```suggestion
    public CategoryDto createCategory(@RequestBody @Valid CategoryRequestDto categoryRequestDto) {
```

2023-12-11 08:11 UTC, Elena-Bruyako commented on src/main/java/onlinebookstore/controler/CategoryController.java
> +    public List<CategoryDto> getAll() {
```suggestion
    public List<CategoryDto> getAll(@ParameterObject @PageableDefault Pageable pageable) {
```

2023-12-11 08:11 UTC, Elena-Bruyako commented on src/main/java/onlinebookstore/controler/CategoryController.java
> +    public CategoryDto getCategoryById(@PathVariable Long id) {
```suggestion
    public CategoryDto getCategoryById(@PathVariable @Positive Long id) {
```

2023-12-11 08:11 UTC, Elena-Bruyako commented on src/main/java/onlinebookstore/dto/book/CreateBookRequestDto.java
> +        List<Long> categoryIds) {
```suggestion
        List<@Positive Long> categoryIds) {
```

2023-12-11 08:11 UTC, Elena-Bruyako commented on src/main/java/onlinebookstore/mapper/CategoryMapper.java
> +    Category toEntity(CategoryRequestDto categoryDto);
```suggestion
    Category toCategory(CategoryRequestDto categoryDto);
```

2023-12-11 08:11 UTC, Elena-Bruyako commented on src/main/java/onlinebookstore/repository/BookRepository.java
> +
```suggestion
```

2023-12-11 08:11 UTC, Elena-Bruyako commented on src/main/java/onlinebookstore/service/impl/CategoryServiceImpl.java
> +                .orElseThrow();
```suggestion
                .orElseThrow(() -> new EntityNotFoundException(.......);
```

2023-12-11 08:11 UTC, Elena-Bruyako commented on src/main/resources/db/changelog/changes/06-create-category-table.yaml
> +                  type: VARCHAR(2000)
```suggestion
                  type: VARCHAR(255)
```
2000 - it's too big size.

2023-12-11 08:11 UTC, Elena-Bruyako commented on src/main/resources/db/changelog/changes/06-create-category-table.yaml
> +                    nullable: false
add empty line at the end of file
Check all changelogs

2023-12-14 10:31 UTC, liliia-ponomarenko approved these changes
Good job! But fix the conflict before merging ;)

2024-01-25 01:43 UTC, closed without merging