Web branch
DenisBogusevich/Online_Book_Store pull request #2
Opened 2023-10-20 00:32 UTC by DenisBogusevich

2023-10-20 08:54 UTC, pavlov-n approved these changes
Good job, i left some minor comments <3

2023-10-20 08:54 UTC, pavlov-n commented on src/main/java/onlinebookstore/service/impl/BookServiceImpl.java
> +    public BookDto getBookById(Long id) {
I'm not sure, but maybe you need to name it findById(), cause of throwing exception

2023-10-20 08:54 UTC, pavlov-n commented on src/main/java/onlinebookstore/service/impl/BookServiceImpl.java
> +                                    + "book with id:" + id));
You can use here .formated()

2023-10-20 08:54 UTC, pavlov-n commented on src/main/java/onlinebookstore/service/impl/BookServiceImpl.java
> +    public Book save(CreateBookRequestDto book) {
As i know you need to return BookDto, not Book

2023-10-20 08:54 UTC, pavlov-n commented on src/main/java/onlinebookstore/dto/BookDto.java
> +    private String coverImage;
i think it should be like this:
```suggestion
    private String title;
    private String author;
    private String isbn;
    private BigDecimal price;
    private String description;
    private String coverImage;
```

2023-10-20 08:54 UTC, pavlov-n commented on src/main/java/onlinebookstore/controler/BookControler.java
> +    public Book createBook(@RequestBody CreateBookRequestDto bookDto) {
May be you should return BookDto here

2023-10-24 08:47 UTC, liliia-ponomarenko requested changes
Good job! Let’s fix a few mistakes ;)

2023-10-24 08:47 UTC, liliia-ponomarenko commented on src/main/java/onlinebookstore/dto/BookDto.java
> +public class BookDto {
Let’s  use records for dtos

2023-10-24 08:47 UTC, liliia-ponomarenko commented on src/main/java/onlinebookstore/repository/impl/BookRepositoryImpl.java
> +public class BookRepositoryImpl implements BookRepository {
you can use RequiredArgsConstructor

2023-10-24 08:47 UTC, liliia-ponomarenko commented on src/main/java/onlinebookstore/repository/impl/BookRepositoryImpl.java
> +        } catch (Exception e) {
Can you use try-with-resources?

2023-10-24 08:47 UTC, liliia-ponomarenko commented on pom.xml
> +        </dependency>
why do you duplicate this dependency?

2023-11-08 14:55 UTC, liliia-ponomarenko approved these changes
Good job!

2023-11-08 14:55 UTC, liliia-ponomarenko commented on src/main/java/onlinebookstore/dto/BookDto.java
> +
```suggestion
```

2023-12-05 14:57 UTC, merged