Data branch
DenisBogusevich/Online_Book_Store pull request #3
Opened 2023-10-22 23:58 UTC by DenisBogusevich

2023-10-23 08:52 UTC, pavlov-n requested changes

2023-10-23 08:52 UTC, pavlov-n commented on src/main/java/onlinebookstore/repository/BookRepository.java
> +public interface BookRepository extends JpaRepository<Book, Long> {
@ Repository missed

2023-10-23 08:52 UTC, pavlov-n commented on src/main/java/onlinebookstore/service/impl/BookServiceImpl.java
> +
Redundant empty lines

2023-10-23 08:52 UTC, pavlov-n commented on src/main/java/onlinebookstore/dto/BookDto.java
> +public class BookDto {
It would be better like record, not class

2023-10-23 08:52 UTC, pavlov-n commented on src/main/java/onlinebookstore/dto/CreateBookRequestDto.java
> +public class CreateBookRequestDto {
same as with BookDto

2023-10-23 08:52 UTC, pavlov-n commented on src/main/java/onlinebookstore/service/impl/BookServiceImpl.java
> +        return bookMapper.toDto(bookRepository.save(book));
I think that this method should update the information in book with some id. Not updating the book's id

2023-10-23 08:53 UTC, pavlov-n commented
And i missed 1 thing, try to find were you have CI error

2023-10-30 15:02 UTC, liliia-ponomarenko requested changes
Good job! Let’s  fix a few mistakes;)

2023-10-30 15:02 UTC, liliia-ponomarenko commented on pom.xml
> +        </dependency>
Do you really need all these dependencies?

2023-10-30 15:02 UTC, liliia-ponomarenko commented on pom.xml
> +</project>
Let’s  add one empty line

2023-10-30 15:02 UTC, liliia-ponomarenko commented on src/main/java/onlinebookstore/exception/DataProcessingException.java
> +    public DataProcessingException(String s, Exception e) {
Don’t  use abbreviations

2023-10-30 15:02 UTC, liliia-ponomarenko commented on src/main/java/onlinebookstore/service/BookService.java
> +
```suggestion
```

2023-10-30 15:02 UTC, liliia-ponomarenko commented on src/main/resources/db/changelog/changes/01-create-books-table.yaml
> +                    nullable: false
the same let's add one empty line

2023-10-30 15:02 UTC, liliia-ponomarenko commented on src/main/resources/db/changelog/db.changelog-master.yaml
> +        file: db/changelog/changes/01-create-books-table.yaml
and here

2023-11-08 08:12 UTC, NazarSmith228 requested changes
Good job! Let's improve your solution

2023-11-08 08:12 UTC, NazarSmith228 commented on pom.xml
> +            <version>4.23.0</version>
you don't need to specify this version

2023-11-08 08:12 UTC, NazarSmith228 commented on pom.xml
> +            <version>4.23.0</version>
this is a plugin - please remove from dependencies section

2023-11-08 08:12 UTC, NazarSmith228 commented on src/main/java/onlinebookstore/controler/BookControler.java
> +    public BookDto createBook(@RequestBody CreateBookRequestDto bookDto) {
makes sense to add CREATED response status

2023-11-08 08:12 UTC, NazarSmith228 commented on src/main/java/onlinebookstore/exception/DataProcessingException.java
> +    public DataProcessingException(String s, Exception e) {
```suggestion
    public DataProcessingException(String message, Throwable cause) {
```

2023-11-08 08:12 UTC, NazarSmith228 commented on src/main/java/onlinebookstore/service/impl/BookServiceImpl.java
> +        var existingBook = findById(id);
```suggestion
        Book existingBook = findById(id);
```

2023-11-08 08:12 UTC, NazarSmith228 commented on src/main/java/onlinebookstore/service/impl/BookServiceImpl.java
> +        book.setId(id);
this is wrong

you should use `existingBook` and update it via mapstruct:
```
void updateBook (CreateBookRequestDto dto, @MappingTarget Book book)
```

so it should be like:
```
Book existingBook = findById(id);
bookMapper.updateBook(bookDto, existingBook);
return bookMapper.toDto(bookRepository.save(existingBook));
```

2023-11-10 11:03 UTC, liliia-ponomarenko approved these changes
Good job! But fix a few mistakes before merging ;)

2023-11-10 11:03 UTC, liliia-ponomarenko commented on src/main/java/onlinebookstore/dto/CreateBookRequestDto.java
> +        String isbn,
better use NotBlank with strings

2023-11-10 11:03 UTC, liliia-ponomarenko commented on src/main/java/onlinebookstore/mapper/BookMapper.java
> +
```suggestion
    void updateBook(CreateBookRequestDto updatedRequestDto, @MappingTarget Book bookToUpdate);
}
```

2023-12-05 14:57 UTC, merged