Global ex
DenisBogusevich/Online_Book_Store pull request #4
Opened 2023-10-24 12:56 UTC by DenisBogusevich

2023-10-27 11:20 UTC, pavlov-n approved these changes
Looks good. But i have one comment for you. Try to rebase your pr to other branches, because while you are not merged them, it's hard to understand what i need to check.
P.s.Who will check, say please, if i'm wrong

2023-10-27 11:20 UTC, pavlov-n commented on src/main/java/onlinebookstore/exception/CustomGlobalExceptionHandler.java
> +
I think that you can to catch your EntityNotFoundException here

2023-11-02 12:04 UTC, liliia-ponomarenko requested changes
good job! Let’s  fix a few mistakes;)

2023-11-02 12:04 UTC, liliia-ponomarenko commented on src/main/java/onlinebookstore/controler/BookControler.java
> +@Validated
Do you need this annotation?

2023-11-02 12:04 UTC, liliia-ponomarenko commented on src/main/java/onlinebookstore/dto/CreateBookRequestDto.java
> +        @NotNull
better use NotBlank with strings

2023-11-02 12:04 UTC, liliia-ponomarenko commented on src/main/java/onlinebookstore/dto/CreateBookRequestDto.java
> +        @Min(0)
You can use PositiveOrZero

2023-11-02 12:04 UTC, liliia-ponomarenko commented on src/main/java/onlinebookstore/exception/DataProcessingException.java
> +    }
Don’t  use abbreviations

2023-11-02 12:04 UTC, liliia-ponomarenko commented on src/main/java/onlinebookstore/repository/BookRepository.java
> +
```suggestion
```

2023-11-02 12:04 UTC, liliia-ponomarenko commented on src/main/java/onlinebookstore/service/BookService.java
> +
```suggestion
```

2023-11-02 12:04 UTC, liliia-ponomarenko commented on src/main/resources/db/changelog/changes/01-create-books-table.yaml
> +                    nullable: false
better add one empty line to the end of file (check other files)

2023-11-08 08:34 UTC, NazarSmith228 requested changes
Good job! Let's improve your solution

2023-11-08 08:34 UTC, NazarSmith228 commented on pom.xml
> +        </dependency>
this is redundant, since you've added `spring-boot-starter-validation`

pls remove

2023-11-08 08:34 UTC, NazarSmith228 commented on pom.xml
> +        </dependency>
this is a plugin - pls remove from dependencies section

2023-11-08 08:34 UTC, NazarSmith228 commented on pom.xml
> +            <version>4.23.0</version>
you don't need to specify the version here

2023-11-08 08:34 UTC, NazarSmith228 commented on pom.xml
> +        </dependency>
```suggestion
        <dependency>
            <groupId>com.h2database</groupId>
            <artifactId>h2</artifactId>
            <scope>test</scope>
        </dependency>
```

2023-11-08 08:34 UTC, NazarSmith228 commented on src/main/java/onlinebookstore/controler/BookControler.java
> +    @PostMapping
pls add CREATED response status

2023-11-08 08:34 UTC, NazarSmith228 commented on src/main/java/onlinebookstore/exception/CustomGlobalExceptionHandler.java
> +    protected ResponseEntity<Object> handleMethodArgumentNotValid(
```suggestion
    @Override
    protected ResponseEntity<Object> handleMethodArgumentNotValid(
```

2023-11-08 08:34 UTC, NazarSmith228 commented on src/main/java/onlinebookstore/exception/CustomGlobalExceptionHandler.java
> +public class CustomGlobalExceptionHandler extends ResponseEntityExceptionHandler {
`@ControllerAdvice` is missing

2023-11-08 08:34 UTC, NazarSmith228 commented on src/main/java/onlinebookstore/exception/CustomGlobalExceptionHandler.java
> +        body.put("status", HttpStatus.BAD_REQUEST);
it makes no sense to add status to response body

pls remove

2023-11-08 08:34 UTC, NazarSmith228 commented on src/main/java/onlinebookstore/exception/DataProcessingException.java
> +    public DataProcessingException(String s, Exception e) {
```suggestion
    public DataProcessingException(String message, Throwable cause) {
```

2023-11-09 06:57 UTC, DenisBogusevich commented on src/main/java/onlinebookstore/exception/CustomGlobalExceptionHandler.java
> +    protected ResponseEntity<Object> handleMethodArgumentNotValid(
can`t add this anotation becouse of error

2023-11-10 08:10 UTC, liliia-ponomarenko approved these changes
Good job! But let’s  fix a few mistakes  before merging ;)

2023-11-10 08:10 UTC, liliia-ponomarenko commented on src/main/java/onlinebookstore/exception/CustomGlobalExceptionHandler.java
> +    protected ResponseEntity<Object> handleMethodArgumentNotValid(
Which error? It should  works! Let’s  discuss  in your chat

2023-11-10 08:10 UTC, liliia-ponomarenko commented on pom.xml
> +        </dependency>
not fixed

2023-12-05 14:57 UTC, merged