Security
DenisBogusevich/Online_Book_Store pull request #5
Opened 2023-11-07 20:10 UTC by DenisBogusevich

2023-11-08 11:10 UTC, AlexRosenkreuz requested changes
Good job! Let's improve your solution

2023-11-08 11:10 UTC, AlexVulpine commented on pom.xml
> +            <version>8.0.1.Final</version>
Why do you need this dependency? You already have springboot validator

2023-11-08 11:10 UTC, AlexVulpine commented on pom.xml
> +        <jjwt.version>0.11.2</jjwt.version>
You can update it to 0.12.3

2023-11-08 11:10 UTC, AlexVulpine commented on src/main/java/onlinebookstore/config/SecurityConfig.java
> +                .httpBasic(Customizer.withDefaults())
Why do you need this?

2023-11-08 11:10 UTC, AlexVulpine commented on src/main/java/onlinebookstore/config/SecurityConfig.java
> +                                        antMatcher("/auth/**")
I suggest adding "/swagger-ui/**" and  "/v3/api-docs/**", if you want non-authenticated users to access main swagger page and docs about endpoints

2023-11-08 11:10 UTC, AlexVulpine commented on src/main/java/onlinebookstore/controler/AuthController.java
> +             throws RegistrationException {
Suggest adding @Valid to validate the parameter

2023-11-08 11:10 UTC, AlexVulpine commented on src/main/java/onlinebookstore/controler/AuthController.java
> +    @PostMapping("/register")
To be more informative about your endpoint you can add the @Operation annotation and set description there. Check all the endpoints that doesnt have it, if necessary

2023-11-08 11:10 UTC, AlexVulpine commented on src/main/java/onlinebookstore/controler/BookControler.java
> +    }
Add @ResponseStatus to all your endpoints. It will give more info, if the operation is successful

2023-11-08 11:10 UTC, AlexVulpine commented on src/main/java/onlinebookstore/controler/BookControler.java
> +    public BookDto getBookById(@PathVariable Long id) {
As you already have "Validated" annotation on your controller, now you can add "Positive" annotation to all id's in parameters to further validate the input

2023-11-08 11:10 UTC, AlexVulpine commented on src/main/java/onlinebookstore/dto/CreateBookRequestDto.java
> +        BigDecimal price,
Better to change Min(0) to @PositiveOrZero, if your price can be zero. If not, just add Positive

2023-11-08 11:10 UTC, AlexVulpine commented on src/main/java/onlinebookstore/dto/CreateBookRequestDto.java
> +        String isbn,
You can further validate strings adding Length annotation to them, if you don't users to input infinite strings into db. Also, I suggest changing NotNull to NotBlank, so that empty strings wouldn't be a valid option for input

2023-11-08 11:10 UTC, AlexVulpine commented on src/main/java/onlinebookstore/dto/user/UserLoginRequest.java
> +        String password) {
You don't really need NotBlank annotation as you already have min parameter in Size. Apply to all cases

2023-11-08 11:10 UTC, AlexVulpine commented on src/main/java/onlinebookstore/dto/user/UserRegistrationRequest.java
> +        String password,
You can also validate password using annotation Pattern. There you can add regex and message parameters

2023-11-08 11:10 UTC, AlexVulpine commented on src/main/java/onlinebookstore/security/JwtUtil.java
> +    }
You can actually implement your getClaim method here to avoid duplicate code

2023-11-08 11:10 UTC, AlexVulpine commented on src/main/java/onlinebookstore/security/JwtUtil.java
> +            throw new JwtException("Expired or invalid JWT token");
You can add this message directly to the jwt filter, but it's up to you

2023-11-08 11:10 UTC, AlexRosenkreuz commented on src/main/java/onlinebookstore/security/JwtAuthFilter.java
> +            return bearToken.substring(7);
You can extract parameters to constants here to avoid magic numbers

2023-11-08 11:10 UTC, AlexRosenkreuz commented on src/main/java/onlinebookstore/security/JwtUtil.java
> +        Claims claims = Jwts.parserBuilder()
Claims should be final as you don't want them to change at any time in your project

2023-11-08 11:10 UTC, AlexRosenkreuz commented on src/main/java/onlinebookstore/security/CustomUserDetailsService.java
> +                .orElseThrow(() -> new RuntimeException("Can't find user by email"));
Suggest changing it to UsernameNotFoundException here

2023-11-08 11:10 UTC, AlexRosenkreuz commented on src/main/resources/application.properties
> +jwt.expiration=5000000
Add property  open-in-view: false

2023-11-21 11:13 UTC, liliia-ponomarenko requested changes
I see changes from previous tasks, let’s fix it! See issue in question channel (massage pinned)

2023-12-05 15:03 UTC, merged